apiVersion: v1
kind: Service
metadata:
  name: my-nodejs-service
spec:
  selector:
    app: my-nodejs-app
  ports:
    - protocol: TCP
      port: 80  # Port on which the service will be exposed
      targetPort: 8080  # Port on which your Node.js application is running inside the container
  type: LoadBalancer  # Change this to NodePort or ClusterIP if needed
