name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Azure Container Registry
        uses: docker/login-action@v1
        with:
          registry: pratsa.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build Docker image
        run: docker build -t your_image_name .

      - name: Tag Docker image
        run: docker tag your_image_name pratsa.azurecr.io/pratsa:${{ github.sha }}

      - name: Push Docker image
        run: docker push pratsa.azurecr.io/pratsa:${{ github.sha }}
