name: Deploy to AKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Azure Container Registry
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}

      - name: Build Docker image
        run: |
          docker build -t backend .
          docker tag backend pratsa.azurecr.io/backend:${{ github.sha }}

      - name: Push Docker image
        run: docker push pratsa.azurecr.io/backend:${{ github.sha }}

      - name: Login to Azure AKS
        uses: azure/aks-set-context@v1
        with:
          creds: ${{ secrets.AZURE_CLIENT_ID }} ${{ secrets.AZURE_CLIENT_SECRET }} ${{ secrets.AZURE_TENANT_ID }}
          cluster-name: pratsa
          resource-group: vc9071

      - name: Deploy to AKS
        run: |
          az kubectl set image deployment/backend-deployment backend=pratsa.azurecr.io/backend:${{ github.sha }}
